exclude_patterns:
- "psd-web/db/"
- "psd-web/test/"
- "psd-web/spec/"
- "psd-web/config/initializers/sidekiq.rb"
- "psd-web/app/assets/10-million-password-list-top-1000000.txt"
- "infrastructure/"
- "docker/"
checks:
  return-statements:
    enabled: true
    config:
      threshold: 5
