linters:
  CommentControlStatement:
    enabled: false

  ControlStatementSpacing:
    enabled: true

  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  EmptyControlStatement:
    enabled: true

  EmptyLines:
    enabled: true

  RedundantDiv:
    enabled: true

  LineLength:
    enabled: true
    exclude:
      - 'app/views/layouts/_header.html.slim'
      - 'app/views/layouts/_footer.html.slim'
      - 'app/views/layouts/application.html.slim'
      - 'app/views/investigations/creation_flow/allegation_details.html.slim'
      - 'app/views/investigations/creation_flow/enquiry_details.html.slim'
    max: 120

  FileLength:
    enabled: false
    max: 300

  RuboCop:
    enabled: true
    # These cops are incredibly noisy since the Ruby we extract from Slim
    # templates isn't well-formatted, so we ignore them.
    ignored_cops:
      - Layout/ArrayAlignment
      - Layout/AlignHash
      - Layout/ArgumentAlignment
      - Layout/AlignParameters
      - Layout/HashAlignment
      - Layout/FirstParameterIndentation
      - Layout/IndentationConsistency
      - Layout/IndentationWidth
      - Layout/IndentFirstArrayElement
      - Layout/MultilineArrayBraceLayout
      - Layout/MultilineAssignmentLayout
      - Layout/MultilineHashBraceLayout
      - Layout/MultilineMethodCallBraceLayout
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineMethodDefinitionBraceLayout
      - Layout/MultilineOperationIndentation
      - Layout/TrailingEmptyLines
      - Layout/TrailingWhitespace
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/BlockLength
      - Metrics/BlockNesting
      - Metrics/LineLength
      - Naming/FileName
      - Style/EmptyLineAfterGuardClause
      - Style/FrozenStringLiteralComment
      - Style/IfUnlessModifier
      - Style/LineEndConcatenation
      - Style/Next
      - Style/WhileUntilModifier
      - Style/TrailingCommaInHashLiteral
      - Style/TrailingCommaInArrayLiteral
      - Style/PercentLiteralDelimiters
      - Style/StringLiterals
      # This one flags some false positives in slim files
      - Style/IdenticalConditionalBranches

  Tab:
    enabled: true

  TagCase:
    enabled: true

  TrailingBlankLines:
    enabled: true

  TrailingWhitespace:
    enabled: true
