version: '3'

services:
  db:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"

  psd-web:
    command: bin/rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - .env
  psd-worker:
    env_file:
      - .env
