version: '3'

services:
  psd-web:
    command: tail -f /dev/null
    image: ${DOCKER_ORG}/psd-web:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
      - ~/coverage-cache/psd:/psd-web/coverage
    environment:
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - NOTIFY_API_KEY
  psd-worker:
    command: tail -f /dev/null
    image: ${DOCKER_ORG}/psd-worker:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - elasticsearch
      - redis
    command: elasticsearch:9200
