source "https://rubygems.org"

ruby "3.3.4"
gem "aasm"
gem "active_model_serializers"
gem "active_storage_validations"
gem "ahoy_matey"
gem "aws-sdk-s3"
gem "aws-sdk-s3control"
gem "bootsnap", require: false
gem "caxlsx"
gem "caxlsx_rails"
gem "cf-app-utils"
gem "cssbundling-rails"
gem "devise"
gem "devise-encryptable"
gem "draper"
gem "govuk-components"
gem "govuk_design_system_formbuilder"
gem "govuk-design-system-rails", "~> 0.10.5", github: "OfficeForProductSafetyAndStandards/govuk-design-system-rails"
gem "govuk_notify_rails"
gem "image_processing"
gem "interactor"
gem "jbuilder"
gem "jsbundling-rails"
gem "lograge"
gem "mini_magick"
gem "opensearch-ruby"

# ActionMailer dependencies
gem "net-imap"
gem "net-pop"
gem "net-smtp"

gem "loaf"
gem "matrix"
gem "nokogiri"
gem "pagy"
gem "paper_trail"
gem "pg"
gem "prawn"
gem "prawn-table"
gem "puma", "~> 6.4"
gem "pundit"
gem "rack"
gem "rails", "~> 7.1.3"
gem "redcarpet"
gem "redis-rails"
gem "rollups"
gem "rswag-api"
gem "rswag-ui"
gem "rubyXL"
gem "sassc-rails"
gem "scout_apm"
gem "searchkick"
gem "sentry-rails"
gem "sentry-sidekiq"
gem "sidekiq"
gem "sidekiq-scheduler"
gem "sprockets"
gem "sprockets-rails", require: "sprockets/railtie"
gem "stimulus-rails"
gem "strong_migrations"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw]
gem "validate_email"
gem "wicked"

# PRISM engine
gem "prism", path: "prism"

# OSU Support Portal engine
gem "support_portal", path: "support_portal"

# Report Portal engine
gem "report_portal", path: "report_portal"

group :development, :test do
  gem "awesome_print", "~> 1.9", require: "ap"
  gem "byebug", "~> 11.1"
  gem "dotenv-rails", "~> 3.1"
  gem "faker", "~> 3.4"
  gem "parallel_tests", "~> 4.7.1"
  gem "pry", "~> 0.14"
  gem "pry-byebug", "~> 3.10"
  gem "pry-doc", "~> 1.5"
  gem "rspec-rails"
  gem "rswag-specs"
end

group :development do
  gem "m", "~> 1.6"
  gem "rails-erd"
  gem "solargraph", "~> 0.50"
  gem "spring", "~> 4.2"
  gem "spring-commands-rspec", "~> 1.0"
  gem "web-console"
end

group :test do
  gem "capybara", "~> 3.40"
  gem "capybara-screenshot", "~> 1.0"
  gem "coveralls_reborn"
  gem "database_cleaner", "~> 2.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "launchy", "~> 3.0"
  gem "rails-controller-testing", "~> 1.0"
  gem "roo", "~> 2.10"
  gem "rspec"
  gem "rspec-mocks", "~> 3.13"
  gem "rubocop", "~> 1.64"
  gem "rubocop-govuk", "~> 5.0"
  gem "rubocop-performance", "~> 1.21"
  gem "rubocop-rspec", "~> 3.0", require: false
  gem "selenium-webdriver", "~> 4"
  gem "shoulda-matchers"
  gem "simplecov"
  gem "simplecov-console", "~> 0.9"
  gem "simplecov-lcov"
  gem "super_diff"
  gem "timecop", "~> 0.9"
  gem "webmock", "~> 3.23"
end

gem "data_migrate"
gem "flipper"
gem "flipper-active_record"
gem "flipper-ui"
