---
geographic_scope:
  - Local
  - Regional
  - National
  - EEA wide
  - EU wide
  - Unknown

summary:
  - Ban on the marketing of the product and any accompanying measures
  - Destruction of the product
  - Import rejected at border
  - Making the marketing of the product subject to prior conditions
  - Marking the product with appropriate warnings on the risks
  - Recall of the product from end users
  - Temporary ban on the supply, offer to supply and display of the product
  - Warning consumers of the risks
  - Withdrawal of the product from the market
