extends: airbnb-base
env:
  browser: true
rules:
  "import/no-extraneous-dependencies": "off"
  "import/prefer-default-export": "off"
settings:
  import/resolver:
    node:
      extensions:
        - .scss
      paths:
        - app/assets
