inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-performance

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'config/initializers/devise.rb'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false
