inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - rubocop-performance
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'app/**/*.axlsx'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'config/initializers/devise.rb'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - spec/features/**/* # Multiple expectations are useful in feature spec scenarios and would otherwise be very inefficient and difficult to read
