module Prism
  class Tasks::CreateController < ApplicationController
    include Wicked::Wizard

    before_action :prism_risk_assessment
    before_action :harm_scenario
    before_action :set_wizard_steps
    before_action :setup_wizard
    before_action :validate_step

    def show
      case step
      when :add_a_harm_scenario_and_probability_of_harm
        @harm_scenario.harm_scenario_steps.build if @harm_scenario.harm_scenario_steps.blank?
        @harm_scenario.harm_scenario_steps.each { |hss| hss.build_harm_scenario_step_evidence if hss.harm_scenario_step_evidence.blank? }
      end

      render_wizard
    end

    def update
      case step
      when :add_a_harm_scenario_and_probability_of_harm
        @harm_scenario.assign_attributes(add_a_harm_scenario_and_probability_of_harm_params)
        # We have to save the harm scenario manually here since we need to build the steps
        # if it fails to save.
        unless @harm_scenario.save(context: step)
          @harm_scenario.harm_scenario_steps.build if @harm_scenario.harm_scenario_steps.blank?
          @harm_scenario.harm_scenario_steps.each { |hss| hss.build_harm_scenario_step_evidence if hss.harm_scenario_step_evidence.blank? }
          return render_wizard
        end
      when :choose_hazard_type, :determine_severity_of_harm, :determine_severity_of_harm_casualties, :add_uncertainty_and_sensitivity_analysis, :check_your_harm_scenario
        @harm_scenario.assign_attributes(send("#{step}_params"))
      end

      @harm_scenario.tasks_status[step.to_s] = "completed"

      if params[:draft] == "true" || params[:final] == "true"
        # "Save as draft" or final save button of the section clicked.
        # Manually save, then finish the wizard.
        if @harm_scenario.save(context: step)
          @prism_risk_assessment.complete_create_section! if step == wizard_steps.last
          redirect_to wizard_path(Wicked::FINISH_STEP)
        else
          render_wizard
        end
      elsif params[:harm_scenario][:back_to] == "summary"
        redirect_to wizard_path(:check_your_harm_scenario)
      else
        render_wizard(@harm_scenario, { context: step }, { harm_scenario_id: @harm_scenario.id })
      end
    rescue ActiveRecord::NestedAttributes::TooManyRecords
      # The user has specified more than the maximum number of harm scenario steps.
      # We get around the lack of meaningful feedback to the user
      # by setting a virtual attribute to a value which is then
      # validated by the model so we can show a nice error message.
      if @harm_scenario
        @harm_scenario.too_many_harm_scenario_steps = true
        @harm_scenario.save!(context: step)
      end

      render_wizard
    end

  private

    def prism_risk_assessment
      @prism_risk_assessment ||= Prism::RiskAssessment.includes(:harm_scenarios).find_by!(id: params[:risk_assessment_id], created_by_user_id: current_user.id)
    end

    def harm_scenario
      @harm_scenario ||= @prism_risk_assessment.harm_scenarios.find_by!(id: params[:harm_scenario_id])
    end

    def set_wizard_steps
      self.steps = NORMAL_RISK_CREATE_STEPS
    end

    def validate_step
      # Don't allow access to a step if the step before has not yet been completed.
      # Checks if the step is the first step or the autogenerated "finish" step.
      redirect_to risk_assessment_tasks_path(@prism_risk_assessment) unless (step == previous_step && @prism_risk_assessment.identify_completed?) || step == :wizard_finish || @harm_scenario.tasks_status[previous_step.to_s] == "completed"
    end

    def finish_wizard_path
      risk_assessment_tasks_path(@prism_risk_assessment)
    end

    def choose_hazard_type_params
      params.require(:harm_scenario).permit(:hazard_type, :other_hazard_type, :description, :back_to, :draft)
    end

    def add_a_harm_scenario_and_probability_of_harm_params
      params.require(:harm_scenario).permit(:back_to, :draft, harm_scenario_steps_attributes: [:id, :_destroy, :description, :probability_type, :probability_decimal, :probability_frequency, :probability_evidence, :probability_evidence_description_limited, :probability_evidence_description_strong, { harm_scenario_step_evidence_attributes: %i[id evidence_file] }])
    end

    def determine_severity_of_harm_params
      params.require(:harm_scenario).permit(:severity, :back_to, :draft)
    end

    def determine_severity_of_harm_casualties_params
      params.require(:harm_scenario).permit(:multiple_casualties, :back_to, :draft)
    end

    def add_uncertainty_and_sensitivity_analysis_params
      params.require(:harm_scenario).permit(:level_of_uncertainty, :sensitivity_analysis, :back_to, :draft)
    end

    def check_your_harm_scenario_params
      params.require(:harm_scenario).permit(:confirmed)
    end
  end
end
