module Prism
  class Tasks::IdentifyController < ApplicationController
    include Wicked::Wizard

    before_action :prism_risk_assessment
    before_action :disallow_editing_submitted_prism_risk_assessment
    before_action :set_wizard_steps
    before_action :setup_wizard
    before_action :validate_step

    def show
      case step
      when :add_a_number_of_hazards
        @product_hazard = @prism_risk_assessment.product_hazard || @prism_risk_assessment.build_product_hazard
      end

      render_wizard
    end

    def update
      case step
      when :add_a_number_of_hazards
        @product_hazard = @prism_risk_assessment.product_hazard || @prism_risk_assessment.build_product_hazard
        @product_hazard.assign_attributes(add_a_number_of_hazards_params)
      end

      @prism_risk_assessment.tasks_status[step.to_s] = "completed"
      @prism_risk_assessment.complete_identify_section if step == wizard_steps.last

      if params[:draft] == "true" || params[:final] == "true"
        # "Save as draft" or final save button of the section clicked.
        # Manually save, then finish the wizard.
        if @prism_risk_assessment.save(context: step)
          redirect_to wizard_path(Wicked::FINISH_STEP)
        else
          render_wizard
        end
      else
        render_wizard(@prism_risk_assessment, { context: step })
      end
    end

  private

    def prism_risk_assessment
      @prism_risk_assessment ||= Prism::RiskAssessment.includes(:associated_investigations, :associated_products).find_by!(id: params[:risk_assessment_id], created_by_user_id: current_user.id)
    end

    def disallow_editing_submitted_prism_risk_assessment
      redirect_to view_submitted_assessment_risk_assessment_tasks_path(@prism_risk_assessment) if @prism_risk_assessment.submitted?
    end

    def set_wizard_steps
      self.steps = NORMAL_RISK_IDENTIFY_STEPS
    end

    def validate_step
      # Don't allow access to a step if the step before has not yet been completed.
      # Checks if the step is the first step or the autogenerated "finish" step.
      redirect_to risk_assessment_tasks_path(@prism_risk_assessment) unless (step == previous_step && @prism_risk_assessment.define_completed?) || step == :wizard_finish || @prism_risk_assessment.tasks_status[previous_step.to_s] == "completed"
    end

    def finish_wizard_path
      risk_assessment_tasks_path(@prism_risk_assessment)
    end

    def add_a_number_of_hazards_params
      params.require(:product_hazard).permit(:number_of_hazards, :final)
    end
  end
end
