---
swagger: '2.0'
info:
  title: PSD API
  version: v1
paths:
  "/api/v1/auth":
    post:
      summary: Request an API token
      tags:
      - Request an API token
      consumes:
      - application/json
      parameters:
      - name: email
        in: query
        type: string
      - name: password
        in: query
        type: string
      responses:
        '200':
          description: User authenticated and API token returned
        '401':
          description: Unauthorized
    delete:
      summary: Delete an API token
      description: Delete a users API tokens using a valid PSD account email and password
      tags:
      - Authentication
      consumes:
      - application/json
      parameters:
      - name: email
        in: query
        type: string
      - name: password
        in: query
        type: string
      responses:
        '200':
          description: User API tokens destroyed
        '401':
          description: Unauthorised user
servers:
- url: https://staging.product-safety-database.service.gov.uk
- url: http://localhost:3000
