---
openapi: 3.0.1
info:
  title: PSD API
  version: v1
paths:
  "/api/v1/auth":
    post:
      summary: Request an API token
      tags:
      - Request an API token
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: User authenticated and API token returned
        '401':
          description: Unauthorized
servers:
- url: https://staging.product-safety-database.service.gov.uk
- url: http://localhost:3000
