---
openapi: 3.0.0
info:
  title: PSD API
  version: v1
components:
  schemas:
    new_notification:
      title: New Notification
      type: object
      properties:
        user_title:
          type: string
        complainant_reference:
          type: string
          nullable: true
        reported_reason:
          type: string
          nullable: true
        hazard_type:
          type: string
          nullable: true
        hazard_description:
          type: string
          nullable: true
        non_compliant_reason:
          type: string
          nullable: true
    notification_object:
      title: Notification
      type: object
      properties:
        id:
          type: string
        state:
          type: string
          nullable: true
        product_category:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        user_title:
          type: string
        complainant_reference:
          type: string
          nullable: true
        risk_level:
          type: string
          nullable: true
        reported_reason:
          type: string
          nullable: true
        non_compliant_reason:
          type: string
          nullable: true
        hazard_type:
          type: string
          nullable: true
        hazard_description:
          type: string
          nullable: true
        notifying_country:
          type: string
        overseas_regulator_country:
          type: string
          nullable: true
        is_from_overseas_regulator:
          type: boolean
        is_closed:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
      required:
      - id
    product_object:
      title: Product
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        brand:
          type: string
        product_code:
          type: string
          nullable: true
        barcode:
          type: string
          nullable: true
        category:
          type: string
        subcategory:
          type: string
          nullable: true
        description:
          type: string
        country_of_origin:
          type: string
        webpage:
          type: string
          nullable: true
        owning_team:
          type: object
          properties:
            name:
              type: string
              nullable: true
            email:
              type: string
              nullable: true
        product_images:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
      required:
      - name
paths:
  "/api/v1/auth":
    post:
      summary: Request an API token
      tags:
      - Authentication
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: User authenticated and API token returned
        '401':
          description: Unauthorized
    delete:
      summary: Delete an API token
      description: Delete a users API tokens using a valid PSD account email and password
      tags:
      - Authentication
      parameters:
      - name: email
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: User API tokens destroyed
        '401':
          description: Unauthorised user
  "/api/v1/notifications/{id}":
    get:
      summary: Retrieves a Notification
      description: Retrieves a Notification's detail by ID
      tags:
      - Notifications
      security:
      - bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Notification found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/notification_object"
        '404':
          description: Notification not found
        '401':
          description: Unauthorised user
  "/api/v1/notifications":
    post:
      summary: Creates a draft Notification
      description: Creates a draft Notification in PSD
      tags:
      - Notifications
      security:
      - bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Notification created
        '406':
          description: Notification not valid
        '401':
          description: Unauthorised user
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_notification"
            examples:
              notification:
                summary: An non-compliant notification
                value:
                  notification:
                    user_title: Turbo vac 3000
                    reported_reason: non_compliant
                    non_compliant_reason: No earth pin on mains plug
  "/api/v1/products/{id}":
    get:
      summary: Retrieves a Product
      description: Retrieves a Product's detail by ID
      tags:
      - Products
      security:
      - bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/product_object"
        '404':
          description: Product not found
        '401':
          description: Unauthorised user
  "/api/v1/products":
    get:
      summary: Search for a Product
      description: Search for a Product
      tags:
      - Products
      security:
      - bearer: []
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: q
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Search results returned
