default: &default
  :url: <%= ENV.fetch('OPENSEARCH_URL', "https://localhost:9200") %>
  :transport_options:
    :request:
      :timeout: 5

development:
  <<: *default
  :transport_options:
    :ssl:
      :verify: false

test:
  <<: *default
  :log: true
  :transport_options:
    :request:
      :timeout: 15
    :ssl:
      :verify: false

production:
  :url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("psd-opensearch-1")["uri"] %>
