inherit_from: .rubocop_todo.yml

inherit_gem:
  govuk-lint: configs/rubocop/all.yml

require: rubocop-performance

AllCops:
  Exclude:
    - './../../app/**/*.axlsx'
    - './../../bin/**/*'
    - './../../coverage/**/*'
    - './../../db/schema.rb'
    - './../../log/**/*'
    - './../../node_modules/**/*'
    - './../../tmp/**/*'
    - 'bin/**/*'
    - './node_modules/**/*'

Rails:
  Enabled: true
