version: 1

update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "javascript"
    directory: "/psd-web"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/shared-web"
    update_schedule: "live"
    default_labels:
    - dependencies
    - javascript
    - fixme

  - package_manager: "ruby:bundler"
    directory: "/infrastructure/fluentd"
    update_schedule: "live"

  - package_manager: "ruby:bundler"
    directory: "/psd-web"
    update_schedule: "live"

  - package_manager: "ruby:bundler"
    directory: "/shared-web"
    update_schedule: "live"
    default_labels:
    - dependencies
    - ruby
    - fixme
