---
legislation:
  - General Product Safety Regulations 2005
  - Gas Appliances (Enforcement) and Miscellaneous Amendments Regulations 2018 / EU 2016/426 Appliances Burning Gaseous Fuels
  - Personal Protective Equipment (Enforcement) Regulations 2018 / EU 2016/425 Personal Protective Equipment
  - Radio Equipment Regulations 2017
  - Recreational Craft Regulations 2017
  - Electrical Equipment (Safety) Regulations 2016
  - Electromagnetic Compatibility Regulations 2016
  - Equipment and Protective Systems Intended for Use in Potentially Explosive Atmospheres Regulations 2016
  - Lifts Regulations 2016
  - Pressure Equipment Regulations 2016
  - Simple Pressure Vessels (Safety) Regulations 2016
  - Pyrotechnic Articles (Safety) Regulations 2015
  - Cosmetic Products Enforcement Regulations 2013 / EC 1223/2009 Cosmetic Products
  - Toys Safety Regulations 2011
  - Aerosol Dispensers Regulations 2009
  - Supply of Machinery (Safety) Regulations 2008
  - Fireworks Act 2003 / Fireworks Regulations 2004
  - Noise Emission in the Environment by Equipment for Use Outdoors Regulations 2001
  - Plugs and Sockets (Safety) Regulations 1994
  - Food Imitations (Safety) Regulations 1989
  - Furniture and Furnishings (Fire) (Safety) Regulations 1988
  - Consumer Protection Act 1987 (Part 1)
  - Nightwear Safety Regulations 1985
  - Oil Heaters (Safety) Regulations 1977
  - Gun Barrel Proof Acts 1868 to 1978
