name: Delete all review apps

on:
  pull_request:
    types: [closed]

jobs:
  cleanup_reviewapp:
    name: Delete all review apps
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    env:
      CF_USERNAME: ${{ secrets.PaaSUsernameInt }}
      CF_PASSWORD: ${{ secrets.PaaSPasswordInt }}

    steps:
    - name: Install cf client
      env:
        CF_CLI_VERSION: v7
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -A "" -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=${CF_CLI_VERSION}" | tar -zx -C $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Delete all review apps
      run: |
        cf api api.london.cloud.service.gov.uk
        cf auth
        cf target -o 'beis-opss' -s $SPACE
        for app in $(cf apps | grep 'psd-pr-' | awk '{print $1}'); do
          cf stop $app
          cf run-task $app --command "./env/delete-opensearch-indexes.sh" --name delete-opensearch-indexes
          task_status=0; until [ $task_status = "SUCCEEDED" ]; do task_status="$(cf tasks $app | grep delete-opensearch-indexes | awk '{print $3}')" && if [ "$task_status" = "FAILED" ]; then break; else echo "waiting" && sleep 10; fi; done;
          cf delete -f -r $app
          cf delete-service -f ${app/psd-pr-/psd-db-pr-}
        done
        cf logout

    - name: Checkout code to get deploy functions
      uses: actions/checkout@v4

    - name: Deactivate GitHub deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source deploy-github-functions.sh
        gh_deploy_deactivate_dangling all-review-apps
