name: Security warnings

on: [push]

jobs:
  ruby:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install brakeman
      run: gem install brakeman
    - name: Run brakeman
      run: brakeman
