name: Smoke test
on: [push]

env:
  DATABASE_URL: postgres://postgres@localhost:5432
  ELASTICSEARCH_URL: http://localhost:9200
  REDIS_URL: redis://localhost:6379
  RAILS_ENV: test
  ANTIVIRUS_URL: http://localhost:3006/safe
  ANTIVIRUS_USERNAME: av
  ANTIVIRUS_PASSWORD: password
  PSD_HOST: example.com
  EMAIL_WHITELIST_ENABLED: false
  TWO_FACTOR_AUTHENTICATION_ENABLED: false
  CI: true

jobs:
  ruby:
    name: "Ruby"
    runs-on: ubuntu-latest

    # Example for can be found here:
    # https://github.com/actions/example-services/tree/master/.github/workflows
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      elasticsearch:
        image: elasticsearch:7.9.2
        ports: ["9200:9200"]
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.x
    # required to compile pg ruby gem
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-no-dev-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install RubyGems
      run: |
        gem install bundler --no-doc
        bundle config path vendor/bundle
        bundle check || bundle install --without development --jobs=4 --retry=3

    - name: Install yarn
      run: npm install yarn -g

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Node.js dependencies
      run: yarn install

    - name: Prepare database
      run: bin/rails parallel:load_schema

    - name: Run Smoke Tests
      env:
        ELASTICSEARCH_URL: localhost
        RAILS_ENV: test
        SMOKE_USER: ${{secrets.SMOKE_SEARCH_USER}}
        SMOKE_SEARCH_PASSWORD: ${{secrets.SMOKE_SEARCH_PASSWORD}}
        SMOKE_RELAY_CODE_URL: ${{secrets.SMOKE_RELAY_CODE_URL}}
        SMOKE_RELAY_CODE_USER: ${{secrets.SMOKE_RELAY_CODE_USER}}
        SMOKE_RELAY_CODE_PASS: ${{secrets.SMOKE_RELAY_CODE_PASS}}
        RUN_SMOKE: "true"

      run: |
        cd psd-web
        bundle exec rspec spec/smoke/search_smoke_test_spec.rb
